In [17]:
import pandas as pd
df=pd.read_csv('healthcare_dataset.csv')
print(df.head(21))

    patient_id   age   gender  blood_pressure glucose  cholesterol    bmi  \
0          103  83.0      NaN           146.0     168        137.0  11.95
1          107  52.0     Male           180.0     154        158.0  36.07
2           72  91.0      NaN           100.0     290        309.0  22.33
3          189  18.0        F           132.0     137        127.0  18.13
4           21  93.0  Unknown           139.0     101        351.0  34.94
5          103  69.0  Unknown           169.0     164        241.0  33.82
6          122  37.0     Male           172.0     177        251.0  49.02
7          215  47.0        M           169.0     209        233.0  25.59
8           88  47.0      NaN           141.0     156        175.0  24.98
9          100  84.0   Female           106.0     275        107.0  24.98
10         152  27.0  Unknown           101.0     137        312.0  17.14
11         131  80.0      NaN           113.0     255        277.0  21.04
12         150  72.0      NaN           107.0     155        241.0  21.10
13         258  52.0  Unknown           106.0     177        233.0  10.07
14         192  88.0        M            89.0     269        347.0  52.18
15         161  56.0        M           177.0     184        374.0  32.88
16          22  33.0        F           177.0     125        125.0  43.33
17         253  18.0      NaN           126.0     106        185.0  47.43
18         236  57.0        F           146.0     109        266.0    NaN
19          49  20.0      NaN            99.0     108        247.0  19.85
20          59  49.0      NaN           110.0     291        141.0  10.07

   smoker  exercise_mins_week disease_risk
0       0                43.0       -0.294
1       1                61.0        1.475
2     yes               250.0        0.132
3     NaN               234.0        0.334
4       1               127.0        0.657
5     NaN               186.0        1.439
6       1                11.0        1.247
7     yes                35.0        0.654
8     yes                38.0        0.613
9      no               180.0        0.485
10    NaN               213.0        0.865
11      1                11.0        1.165
12     no                -3.0        0.284
13      1               110.0       -0.213
14     no               161.0        0.317
15    yes                98.0       -0.174
16    NaN                -8.0        0.751
17     no               261.0        1.075
18      1               107.0        0.304
19      1               252.0          0.8
20    NaN                19.0        0.727

In [18]:
df['age']=pd.to_numeric(df['age'],errors='coerce')
df.dropna(subset=['age'],inplace =True)
df['age']=df['age'].astype(int)
df.dropna(subset=['gender'],inplace =True)
df['gender'].replace({'M':'Male','F':'Female','Unknown':'Others'},inplace=True)
a=df['blood_pressure'].mean()
df.fillna({'blood_pressure':a},inplace=True)
df['blood_pressure']=df['blood_pressure'].astype(int)
df['glucose']=pd.to_numeric(df['glucose'],errors='coerce')
b=df['glucose'].mean()
df.fillna({'glucose':b},inplace =True)
df['glucose']=df['glucose'].astype(int)
df.dropna(subset=('cholesterol'),inplace=True)
c=df['bmi'].mean()
df.fillna({'bmi':c},inplace=True)
df['bmi']=df['bmi'].astype(int)
df=df[df['exercise_mins_week'] >= 0]
df['exetcise_mins_week']=df['exercise_mins_week'].astype(int)
df["disease_risk"] = pd.to_numeric(df["disease_risk"], errors="coerce")
df["disease_risk"] =df['disease_risk']
d=df['disease_risk'].mean()
df.fillna({'disease_risk':d},inplace=True)
# df['disease_risk']=df['disease_risk'].astype(int)
df=df[df['disease_risk'] >= 0 ]
df["smoker"] = (
    df["smoker"]
        .astype(str).str.lower().str.strip()
        .map({
            "1": 1, "yes": 1, "y": 1,
            "0": 0, "no": 0, "n": 0,
            "": None, "none": None, "nan": None
        })
)
df["smoker"] = pd.to_numeric(df["smoker"], errors="coerce")
df.dropna(subset=('smoker'),inplace =True)
print(df.head())
df.to_csv(('clean_healthcare.csv'),index=False)

   patient_id  age  gender  blood_pressure  glucose  cholesterol  bmi  smoker  \
1         107   52    Male             180      154        158.0   36     1.0
4          21   93  Others             139      101        351.0   34     1.0
6         122   37    Male             172      177        251.0   49     1.0
7         215   47    Male             169      209        233.0   25     1.0
9         100   84  Female             106      275        107.0   24     0.0

   exercise_mins_week  disease_risk  exetcise_mins_week
1                61.0         1.475                  61
4               127.0         0.657                 127
6                11.0         1.247                  11
7                35.0         0.654                  35
9               180.0         0.485                 180

C:\Users\Deep\AppData\Local\Temp\ipykernel_19712\1355250180.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].replace({'M':'Male','F':'Female','Unknown':'Others'},inplace=True)

In [19]:
df = df.drop(columns=['exetcise_mins_week'])
df.head()

,patient_id,age,gender,blood_pressure,glucose,cholesterol,bmi,smoker,exercise_mins_week,disease_risk
1,107,52,Male,180,154,158.0,36,1.0,61.0,1.475
4,21,93,Others,139,101,351.0,34,1.0,127.0,0.657
6,122,37,Male,172,177,251.0,49,1.0,11.0,1.247
7,215,47,Male,169,209,233.0,25,1.0,35.0,0.654
9,100,84,Female,106,275,107.0,24,0.0,180.0,0.485

Who are the patients that need immediate preventive care?

In [21]:
df['risk_segment']=pd.qcut(df['disease_risk'],q=5,labels=False)
high_risk_patients=df[df['risk_segment'] == 4]
high_risk_patients[['patient_id','age','disease_risk']].sort_values(by='disease_risk',ascending=False)

     patient_id  age  disease_risk
116          28   61         1.491
302         147   50         1.484
204         113   33         1.477
319          89   52         1.477
296         196   50         1.477
1           107   52         1.475
197         131   69         1.457
118          44   78         1.455
257          54   40         1.449
264         104   46         1.439
92           42   77         1.394
159         247   67         1.377
147         130   39         1.335
191         160   38         1.330
75           33   90         1.301
6           122   37         1.247
311          58   41         1.241
247          99   20         1.201
51          190   18         1.200
60          157   48         1.199
265         246   65         1.199
313           1   15         1.194
316         126   83         1.170

Which patients have multiple high-risk indicators?

In [28]:
high_attention_patients=df[
(df['disease_risk'] > df['disease_risk'].mean()) &
(df['bmi'] >30) &
(df['blood_pressure'] >140)
]
high_attention_patients[['patient_id', 'age', 'bmi', 'blood_pressure', 'disease_risk']]\
.sort_values(by='disease_risk',ascending=False)

     patient_id  age  bmi  blood_pressure  disease_risk
1           107   52   36             180         1.475
264         104   46   54             151         1.439
147         130   39   31             192         1.335
191         160   38   50             175         1.330
75           33   90   54             156         1.301
6           122   37   49             172         1.247
51          190   18   52             143         1.200
60          157   48   37             143         1.199
66           63   83   35             195         1.015
106          13   80   32             168         0.958
152         126   50   57             172         0.924
216          68   89   48             193         0.885
146           2   93   58             180         0.878
141         101   48   32             154         0.853
221         176   59   39             144         0.819

Which factors influence disease risk the most?

In [29]:
df.corr(numeric_only=True)['disease_risk'] \
  .sort_values(ascending=False)

disease_risk          1.000000
risk_segment          0.973752
glucose               0.147575
blood_pressure        0.041462
age                   0.013707
smoker               -0.017366
exercise_mins_week   -0.032624
bmi                  -0.083258
cholesterol          -0.118212
patient_id           -0.207121
Name: disease_risk, dtype: float64